// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package broker is a generated GoMock package.
package broker

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ibeloyar/gophprofile/internal/model"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateAvatar mocks base method.
func (m *MockStorage) CreateAvatar(ctx context.Context, userID, fileName, mimeType string, width, height int, sizeBytes int64) (*model.AvatarCreateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvatar", ctx, userID, fileName, mimeType, width, height, sizeBytes)
	ret0, _ := ret[0].(*model.AvatarCreateInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAvatar indicates an expected call of CreateAvatar.
func (mr *MockStorageMockRecorder) CreateAvatar(ctx, userID, fileName, mimeType, width, height, sizeBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvatar", reflect.TypeOf((*MockStorage)(nil).CreateAvatar), ctx, userID, fileName, mimeType, width, height, sizeBytes)
}

// GetAvatarByID mocks base method.
func (m *MockStorage) GetAvatarByID(ctx context.Context, avatarID, userID string) (*model.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarByID", ctx, avatarID, userID)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarByID indicates an expected call of GetAvatarByID.
func (mr *MockStorageMockRecorder) GetAvatarByID(ctx, avatarID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarByID", reflect.TypeOf((*MockStorage)(nil).GetAvatarByID), ctx, avatarID, userID)
}

// GetAvatarMeta mocks base method.
func (m *MockStorage) GetAvatarMeta(ctx context.Context, avatarID, userID string) (*model.AvatarMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarMeta", ctx, avatarID, userID)
	ret0, _ := ret[0].(*model.AvatarMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarMeta indicates an expected call of GetAvatarMeta.
func (mr *MockStorageMockRecorder) GetAvatarMeta(ctx, avatarID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarMeta", reflect.TypeOf((*MockStorage)(nil).GetAvatarMeta), ctx, avatarID, userID)
}

// Health mocks base method.
func (m *MockStorage) Health() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockStorageMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockStorage)(nil).Health))
}

// Shutdown mocks base method.
func (m *MockStorage) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockStorageMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockStorage)(nil).Shutdown))
}

// SoftDeleteAvatar mocks base method.
func (m *MockStorage) SoftDeleteAvatar(ctx context.Context, avatarID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAvatar", ctx, avatarID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAvatar indicates an expected call of SoftDeleteAvatar.
func (mr *MockStorageMockRecorder) SoftDeleteAvatar(ctx, avatarID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAvatar", reflect.TypeOf((*MockStorage)(nil).SoftDeleteAvatar), ctx, avatarID, userID)
}

// UpdateAvatarS3Key mocks base method.
func (m *MockStorage) UpdateAvatarS3Key(ctx context.Context, id, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarS3Key", ctx, id, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatarS3Key indicates an expected call of UpdateAvatarS3Key.
func (mr *MockStorageMockRecorder) UpdateAvatarS3Key(ctx, id, s3Key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarS3Key", reflect.TypeOf((*MockStorage)(nil).UpdateAvatarS3Key), ctx, id, s3Key)
}

// MockS3Storage is a mock of S3Storage interface.
type MockS3Storage struct {
	ctrl     *gomock.Controller
	recorder *MockS3StorageMockRecorder
}

// MockS3StorageMockRecorder is the mock recorder for MockS3Storage.
type MockS3StorageMockRecorder struct {
	mock *MockS3Storage
}

// NewMockS3Storage creates a new mock instance.
func NewMockS3Storage(ctrl *gomock.Controller) *MockS3Storage {
	mock := &MockS3Storage{ctrl: ctrl}
	mock.recorder = &MockS3StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Storage) EXPECT() *MockS3StorageMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockS3Storage) Download(ctx context.Context, objectKey string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, objectKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Download indicates an expected call of Download.
func (mr *MockS3StorageMockRecorder) Download(ctx, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockS3Storage)(nil).Download), ctx, objectKey)
}

// Health mocks base method.
func (m *MockS3Storage) Health() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockS3StorageMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockS3Storage)(nil).Health))
}

// Upload mocks base method.
func (m *MockS3Storage) Upload(ctx context.Context, objectKey, contentType string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, objectKey, contentType, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockS3StorageMockRecorder) Upload(ctx, objectKey, contentType, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockS3Storage)(nil).Upload), ctx, objectKey, contentType, data)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockPublisher) Health() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockPublisherMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockPublisher)(nil).Health))
}

// PublishDelete mocks base method.
func (m *MockPublisher) PublishDelete(ctx context.Context, event *model.AvatarDeleteEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDelete", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDelete indicates an expected call of PublishDelete.
func (mr *MockPublisherMockRecorder) PublishDelete(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDelete", reflect.TypeOf((*MockPublisher)(nil).PublishDelete), ctx, event)
}

// PublishUpload mocks base method.
func (m *MockPublisher) PublishUpload(ctx context.Context, event *model.AvatarUploadEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUpload", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUpload indicates an expected call of PublishUpload.
func (mr *MockPublisherMockRecorder) PublishUpload(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUpload", reflect.TypeOf((*MockPublisher)(nil).PublishUpload), ctx, event)
}

// Shutdown mocks base method.
func (m *MockPublisher) Shutdown() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown")
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockPublisherMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockPublisher)(nil).Shutdown))
}
