// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/controller.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ibeloyar/gophprofile/internal/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockService) DeleteAvatar(ctx context.Context, avatarID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, avatarID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockServiceMockRecorder) DeleteAvatar(ctx, avatarID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockService)(nil).DeleteAvatar), ctx, avatarID, userID)
}

// DownloadAvatar mocks base method.
func (m *MockService) DownloadAvatar(ctx context.Context, avatarID, userID string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadAvatar", ctx, avatarID, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadAvatar indicates an expected call of DownloadAvatar.
func (mr *MockServiceMockRecorder) DownloadAvatar(ctx, avatarID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAvatar", reflect.TypeOf((*MockService)(nil).DownloadAvatar), ctx, avatarID, userID)
}

// GetAvatarMeta mocks base method.
func (m *MockService) GetAvatarMeta(ctx context.Context, avatarID, userID string) (*model.AvatarMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarMeta", ctx, avatarID, userID)
	ret0, _ := ret[0].(*model.AvatarMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarMeta indicates an expected call of GetAvatarMeta.
func (mr *MockServiceMockRecorder) GetAvatarMeta(ctx, avatarID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarMeta", reflect.TypeOf((*MockService)(nil).GetAvatarMeta), ctx, avatarID, userID)
}

// Health mocks base method.
func (m *MockService) Health() *model.HealthResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health")
	ret0, _ := ret[0].(*model.HealthResponse)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockServiceMockRecorder) Health() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockService)(nil).Health))
}

// UploadAvatar mocks base method.
func (m *MockService) UploadAvatar(ctx context.Context, userID string, avatarFile *model.AvatarFile) (*model.AvatarCreateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, avatarFile)
	ret0, _ := ret[0].(*model.AvatarCreateInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockServiceMockRecorder) UploadAvatar(ctx, userID, avatarFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockService)(nil).UploadAvatar), ctx, userID, avatarFile)
}
